USE [master]
GO

/****** Object:  Database [SpainCitiesDb]    Script Date: 3/1/2025 00:51:13 ******/
CREATE DATABASE [SpainCitiesDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SpainCitiesDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SpainCitiesDb.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SpainCitiesDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SpainCitiesDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SpainCitiesDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SpainCitiesDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SpainCitiesDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SpainCitiesDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SpainCitiesDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SpainCitiesDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SpainCitiesDb] SET  MULTI_USER 
GO

ALTER DATABASE [SpainCitiesDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SpainCitiesDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SpainCitiesDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SpainCitiesDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SpainCitiesDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SpainCitiesDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SpainCitiesDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SpainCitiesDb] SET  READ_WRITE 
GO

