USE [SpainCitiesDb]
GO

INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('1','Almería','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('2','Cádiz','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('3','Córdoba','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('4','Granada','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('5','Huelva','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('6','Jaén','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('7','Málaga','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('8','Sevilla','1')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('9','Barcelona','7')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('10','Girona','7')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('11','Lerida','7')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('12','Tarragona','7')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('13','Madrid','8')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('14','Ávila','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('15','Burgos','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('16','León','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('17','Palencia','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('18','Salamanca','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('19','Segovia','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('20','Soria','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('21','Valladolid','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('22','Zamora','5')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('23','Albacete','6')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('24','Ciudad Real','6')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('25','Cuenca','6')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('26','Guadalajara','6')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('27','Toledo','6')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('28','Alicante','10')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('29','Castellón','10')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('30','Valencia','10')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('31','La Coruña','12')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('32','Lugo','12')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('33','Ourense','12')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('34','Pontevedra','12')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('35','Álava','15')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('36','Gipuzkoa','15')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('37','Bizkaia','15')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('38','Huesca','2')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('39','Teruel','2')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('40','Zaragoza','2')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('41','Cantabria','4')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('42','Badajoz','11')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('43','Cáceres','11')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('44','Islas Baleares','13')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('45','Murcia','17')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('46','La Rioja','14')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('47','Navarra','9')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('48','Las Palmas','3')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('49','Santa Cruz de Tenerife','3')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('50','Ceuta','18')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('51','Melilla','19')
INSERT INTO [dbo].[Provinces]([Id],[Name],[RegionId])VALUES('52','Provincia de Asturias','16')
