USE [SpainCitiesDb]
GO

INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('1','Almería','1','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('2','Roquetas de Mar','1','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('3','El Ejido','1','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('4','Níjar','1','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('5','Adra','1','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('6','Cádiz','2','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('7','Jerez de la Frontera','2','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('8','San Fernando','2','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('9','Chiclana de la Frontera','2','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('10','La Línea de la Concepción','2','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('11','Córdoba','3','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('12','Lucena','3','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('13','Puente Genil','3','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('14','Villa del Río','3','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('15','Baena','3','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('16','Granada','4','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('17','Maracena','4','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('18','Almuñécar','4','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('19','Baza','4','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('20','Motril','4','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('21','Huelva','5','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('22','Lepe','5','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('23','Ayamonte','5','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('24','Aljaraque','5','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('25','Punta Umbría','5','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('26','Jaén','6','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('27','Andújar','6','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('28','Úbeda','6','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('29','Baeza','6','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('30','Linares','6','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('31','Málaga','7','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('32','Marbella','7','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('33','Ronda','7','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('34','Vélez-Málaga','7','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('35','Estepona','7','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('36','Sevilla','8','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('37','Dos Hermanas','8','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('38','Alcalá de Guadaíra','8','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('39','Coria del Río','8','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('40','Utrera','8','1')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('41','Barcelona','9','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('42','Badalona','9','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('43','L''Hospitalet de Llobregat','9','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('44','Terrassa','9','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('45','Sabadell','9','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('46','Girona','10','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('47','Figueres','10','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('48','Blanes','10','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('49','Olot','10','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('50','Castelló d''Empúries','10','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('51','Lleida','11','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('52','Tàrrega','11','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('53','Balaguer','11','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('54','Mollerussa','11','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('55','Agramunt','11','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('56','Tarragona','12','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('57','Reus','12','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('58','Salou','12','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('59','Valls','12','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('60','El Vendrell','12','7')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('61','Madrid','13','8')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('62','Alcalá de Henares','13','8')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('63','Fuenlabrada','13','8')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('64','Móstoles','13','8')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('65','Getafe','13','8')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('66','Ávila','14','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('67','El Barco de Ávila','14','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('68','Arévalo','14','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('69','Candeleda','14','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('70','Fontiveros','14','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('71','Burgos','15','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('72','Aranda de Duero','15','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('73','Miranda de Ebro','15','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('74','Briviesca','15','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('75','Belorado','15','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('76','León','16','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('77','Ponferrada','16','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('78','San Andrés del Rabanedo','16','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('79','Astorga','16','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('80','La Bañeza','16','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('81','Palencia','17','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('82','Arroyo de la Encomienda','17','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('83','Villamuriel de Cerrato','17','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('84','Cartes','17','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('85','Aguilar de Campoo','17','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('86','Salamanca','18','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('87','Ciudad Rodrigo','18','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('88','Peñaranda de Bracamonte','18','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('89','Santa Marta de Tormes','18','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('90','Vitigudino','18','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('91','Segovia','19','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('92','Cuéllar','19','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('93','Cantalejo','19','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('94','Agreda','19','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('95','Sepúlveda','19','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('96','Soria','20','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('97','El Burgo de Osma','20','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('98','San Esteban de Gormaz','20','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('99','Duruelo de la Sierra','20','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('100','Agreda','20','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('101','Valladolid','21','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('102','Medina del Campo','21','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('103','Laguna de Duero','21','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('104','Aldeamayor de San Martín','21','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('105','Viana de Cega','21','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('106','Zamora','22','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('107','Benavente','22','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('108','Toro','22','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('109','Fuentesaúco','22','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('110','Villalpando','22','5')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('111','Albacete','23','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('112','Hellín','23','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('113','La Rasa','23','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('114','Chinchilla de Monte-Aragón','23','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('115','Caudete','23','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('116','Ciudad Real','24','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('117','Alcázar de San Juan','24','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('118','Puertollano','24','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('119','Manzanares','24','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('120','Tomelloso','24','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('121','Cuenca','25','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('122','Mota del Cuervo','25','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('123','Tarancón','25','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('124','San Clemente','25','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('125','Las Pedroñeras','25','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('126','Guadalajara','26','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('127','Azuqueca de Henares','26','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('128','Sigüenza','26','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('129','Marchamalo','26','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('130','Fontanar','26','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('131','Toledo','27','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('132','Talavera de la Reina','27','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('133','Illescas','27','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('134','Toledo','27','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('135','Ocaña','27','6')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('136','Alicante','28','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('137','Elche','28','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('138','Torrevieja','28','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('139','Benidorm','28','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('140','Elda','28','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('141','Castellón de la Plana','29','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('142','Vila-real','29','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('143','Burriana','29','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('144','Segorbe','29','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('145','Oropesa del Mar','29','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('146','Valencia','30','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('147','Gandía','30','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('148','Torrent','30','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('149','Paterna','30','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('150','Sagunto','30','10')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('151','La Coruña','31','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('152','Santiago de Compostela','31','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('153','Ferrol','31','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('154','Carballo','31','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('155','Narón','31','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('156','Lugo','32','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('157','Monforte de Lemos','32','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('158','Viveiro','32','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('159','Ribadeo','32','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('160','Vilalba','32','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('161','Ourense','33','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('162','Verín','33','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('163','Ribeira de Piquín','33','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('164','Barbadás','33','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('165','O Carballiño','33','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('166','Pontevedra','34','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('167','Vigo','34','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('168','Sanxenxo','34','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('169','Marín','34','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('170','Redondela','34','12')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('171','Vitoria-Gasteiz','35','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('172','Laguardia','35','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('173','Salvatierra','35','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('174','Amurrio','35','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('175','Laudio','35','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('176','San Sebastián','36','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('177','Irún','36','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('178','Eibar','36','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('179','Tolosa','36','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('180','Hernani','36','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('181','Bilbao','37','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('182','Barakaldo','37','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('183','Getxo','37','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('184','Santurce','37','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('185','Basauri','37','15')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('186','Huesca','38','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('187','Jaca','38','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('188','Fraga','38','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('189','Monzón','38','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('190','Barbastro','38','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('191','Teruel','39','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('192','Alcañiz','39','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('193','Calamocha','39','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('194','Cella','39','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('195','Valderrobres','39','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('196','Zaragoza','40','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('197','Huesca','40','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('198','Teruel','40','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('199','Cuarte de Huerva','40','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('200','La Almunia de Doña Godina','40','2')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('201','Santander','41','4')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('202','Torrelavega','41','4')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('203','Castro Urdiales','41','4')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('204','Colindres','41','4')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('205','Laredo','41','4')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('206','Badajoz','42','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('207','Mérida','42','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('208','Villanueva de la Serena','42','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('209','Don Benito','42','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('210','Olivenza','42','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('211','Cáceres','43','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('212','Plasencia','43','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('213','Badajoz','43','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('214','Trujillo','43','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('215','Navalmoral de la Mata','43','11')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('216','Palma de Mallorca','44','13')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('217','Ibiza','44','13')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('218','Manacor','44','13')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('219','Inca','44','13')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('220','Marratxí','44','13')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('221','Murcia','45','17')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('222','Cartagena','45','17')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('223','Lorca','45','17')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('224','Molina de Segura','45','17')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('225','Cieza','45','17')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('226','Logroño','46','14')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('227','Calahorra','46','14')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('228','Arnedo','46','14')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('229','Nájera','46','14')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('230','Aire','46','14')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('231','Pamplona','47','9')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('232','Tudela','47','9')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('233','Estella','47','9')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('234','Castejón','47','9')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('235','Burlada','47','9')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('236','Las Palmas de Gran Canaria','48','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('237','Telde','48','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('238','Arrecife','48','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('239','Santa Lucía','48','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('240','Ingenio','48','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('241','Santa Cruz de Tenerife','49','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('242','La Laguna','49','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('243','San Cristóbal de La Laguna','49','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('244','Arona','49','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('245','Adeje','49','3')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('246','Ceuta','50','18')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('247','Puerto de Ceuta','50','18')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('248','Mirador de Ceuta','50','18')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('249','Algeciras','50','18')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('250','Monte Hacho','50','18')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('251','Melilla','51','19')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('252','Margarita','51','19')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('253','Bajo','51','19')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('254','Juan Carlos','51','19')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('255','María','51','19')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('256','Oviedo','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('257','Gijón','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('258','Avilés','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('259','Mieres','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('260','Langreo','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('261','Luarca','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('262','Cangas de Onís','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('263','Ribadesella','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('264','Siero','52','16')
INSERT INTO [dbo].[Cities]([Id],[Name],[ProvinceId],[RegionId])VALUES('265','Candás','52','16')








